name: Metrics
on:
  schedule: [{cron: "0 2 * * 3"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: prolixalias/metrics@latest
        with:
          user: prolixalias
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile/metrics.svg
          output_action: pull-request-merge
          plugin_languages: yes
          plugin_followup: yes
          plugin_rss: no
